<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use Paynl\Payment\ViewModel\FastCheckout;
use Yireo\LokiCheckout\ViewModel\CheckoutState;
use Yireo\LokiComponents\Factory\ViewModelFactory;
use Yireo\LokiFieldComponents\ViewModel\ImageOutput;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var FastCheckout $fastCheckout */
/** @var CheckoutState $checkoutState */

$checkoutState = $viewModelFactory->create(CheckoutState::class);
$fastCheckout = $viewModelFactory->create(FastCheckout::class);
if (false === $fastCheckout->getVisibility()) {
    return;
}

$shippingAddress = $checkoutState->getQuote()->getShippingAddress();
$imageOutput = $viewModelFactory->create(ImageOutput::class);
?>
<div x-data="LokiModal">
    <form action="/paynl/checkout/fastcheckoutstart" method="post">
        <input type="hidden" value="<?= $shippingAddress->getCountryId() ?>" name="selected_estimate_country"/>
        <input type="hidden" value="<?= $shippingAddress->getPostcode() ?>" name="selected_estimate_zip"/>

        <?php if ($fastCheckout->modalEnabled()): ?>
            <a @click="toggleModal" :disabled="isModalOpen" title="Fast Checkout"
               class="cursor-pointer rounded-md p-4 bg-[#c90066] text-white flex">
                <?= $imageOutput->get('Paynl_Payment::images/fastCheckoutIdeal.png') ?>
                <span class="pt-4"><?= __('Fast Checkout') ?></span>
            </a>

            <dialog x-ref="modal" class="border border-zinc-200 rounded-lg shadow-lg p-10">
                <div>
                    <a @click="toggleModal" class="float-right m-4 cursor-pointer w-4">
                        <?= $imageOutput->get('Yireo_LokiComponents::images/xmark.svg') ?>
                    </a>

                    <div class="flex flex-wrap">
                        <div class="w-64 p-4">
                            <?= $imageOutput->get('Paynl_Payment::images/ideal-visual.webp') ?>
                        </div>
                        <div class="p-4">
                            <div class="text-3xl">
                                <span class="text-[#cc0066]"><?= __('Order faster') ?></span>
                                <?= __('with iDEAL fast checkout') ?>
                            </div>
                            <div class="my-4">
                                <p><?= __('Create an iDEAL profile and save your address for your next order') ?></p>
                            </div>
                            <button class="w-full bg-[#cc0066] text-white rounded-full p-4 my-2 font-bold" type="submit"
                                    title="Fast Checkout">
                                <?= __('Fast Checkout') ?>
                            </button>
                            <button @click="toggleModal"
                                    class="w-full border border-zinc-400 rounded-full p-4 my-2 font-bold">
                                <?= __('Enter my own address and pay') ?>
                            </button>
                        </div>
                    </div>
                </div>
            </dialog>
        <?php else: ?>
            <button type="submit"
                    title="Fast Checkout"
                    class="action tocart primary paynl-fast_checkout-btn">
                <?= __('Fast Checkout') ?>
            </button>
        <?php endif ?>

        <?php echo $block->getBlockHtml('formkey') ?>
    </form>
</div>
