<?php
declare(strict_types=1);

/** @version 2.0.9 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use LokiCheckout\PayNl\ViewModel\IdealFastCheckout;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Field\ViewModel\ImageOutput;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var IdealFastCheckout $idealFastCheckout */
$idealFastCheckout = $viewModelFactory->create(IdealFastCheckout::class);
$shippingAddress = $idealFastCheckout->getShippingAddress();
$imageOutput = $viewModelFactory->create(ImageOutput::class);
?>
<div x-data="LokiModal">
    <a @click="toggleModal" :disabled="isModalOpen" title="Fast Checkout"
       class="<?= $css('cursor-pointer rounded-md p-4 bg-[#c90066] text-white flex', '@todo') ?>">
        <?= /** @noEscape */ $imageOutput->get('Paynl_Payment::images/fastCheckoutIdeal.png') ?>
        <span class="<?= $css('pt-4', '@todo') ?>"><?= $escaper->escapeHtml(__('Fast Checkout')) ?></span>
    </a>

    <dialog x-ref="modal" class="<?= $css('border border-zinc-200 rounded-lg shadow-lg p-10', '@todo') ?>">
        <div>
            <a @click="toggleModal" class="<?= $css('float-right m-4 cursor-pointer w-4', '@todo') ?>">
                <?= /** @noEscape */ $imageOutput->get('Loki_Components::images/xmark.svg') ?>
            </a>

            <div class="<?= $css('flex flex-wrap', '@todo') ?>">
                <div class="<?= $css('w-64 p-4', '@todo') ?>">
                    <?= /** @noEscape */ $imageOutput->get('Paynl_Payment::images/ideal-visual.webp') ?>
                </div>
                <div class="<?= $css('p-4', '@todo') ?>">
                    <div class="<?= $css('text-3xl', '@todo') ?>">
                        <span class="<?= $css('text-[#cc0066]', '@todo') ?>"><?= $escaper->escapeHtml(__('Order faster')) ?></span>
                        <?= $escaper->escapeHtml(__('with iDEAL fast checkout')) ?>
                    </div>
                    <div class="<?= $css('my-4', '@todo') ?>">
                        <p><?= $escaper->escapeHtml(__('Create an iDEAL profile and save your address for your next order')) ?></p>
                    </div>
                    <form action="/paynl/checkout/fastcheckoutstart" method="post">
                        <input type="hidden" value="<?= $escaper->escapeHtml($shippingAddress->getCountryId()) ?>"
                               name="selected_estimate_country"/>
                        <input type="hidden" value="<?= $escaper->escapeHtml($shippingAddress->getPostcode()) ?>"
                               name="selected_estimate_zip"/>
                        <button class="<?= $css('w-full bg-[#cc0066] text-white rounded-full p-4 my-2 font-bold', '@todo') ?>" type="submit"
                                title="Fast Checkout">
                            <?= $escaper->escapeHtml(__('Fast Checkout')) ?>
                        </button>
                        <?php echo /* @noEscape */ $block->getBlockHtml('formkey') ?>
                    </form>
                    <button @click="toggleModal"
                            class="<?= $css('w-full border border-zinc-400 rounded-full p-4 my-2 font-bold', '@todo') ?>">
                        <?= $escaper->escapeHtml(__('Enter my own address and pay')) ?>
                    </button>
                </div>
            </div>
        </div>
    </dialog>
</div>
