<?php
declare(strict_types=1);

/** @version 2.0.15 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use LokiCheckout\PayNl\ViewModel\IdealFastCheckout;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Block\ImageRenderer;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var IdealFastCheckout $idealFastCheckout */
$idealFastCheckout = $viewModelFactory->create(IdealFastCheckout::class);
$shippingAddress = $idealFastCheckout->getShippingAddress();

?>
<div x-data="LokiModal">
    <a @click.prevent="toggleModal" :disabled="isModalOpen" title="Fast Checkout"
       class="<?= $escaper->escapeHtml($css('cursor-pointer rounded-md p-4 bg-[#c90066] text-white flex', 'modal-trigger')) ?>">
        <?= /* @noEscape */ $imageRenderer->get('Paynl_Payment::images/fastCheckoutIdeal.png') ?>
        <span class="<?= $escaper->escapeHtml($css('pt-4', 'modal-label')) ?>">
            <?= $escaper->escapeHtml(__('Fast Checkout')) ?>
        </span>
    </a>

    <dialog x-ref="modal" class="<?= $escaper->escapeHtml($css('border border-zinc-200 rounded-lg shadow-lg p-10', 'dialog')) ?>">
        <div>
            <a @click.prevent="toggleModal" class="<?= $escaper->escapeHtml($css('float-right m-4 cursor-pointer w-4', 'dialog-close')) ?>">
                <?= /* @noEscape */ $imageRenderer->icon($block, 'xmark') ?>
            </a>

            <div class="<?= $escaper->escapeHtml($css('flex flex-wrap', 'dialog-inner')) ?>">
                <div class="<?= $escaper->escapeHtml($css('w-64 p-4', 'dialog-inner-logo')) ?>">
                    <?= /* @noEscape */ $imageRenderer->get('Paynl_Payment::images/ideal-visual.webp') ?>
                </div>
                <div class="<?= $escaper->escapeHtml($css('p-4', 'dialog-inner-content')) ?>">
                    <div class="<?= $escaper->escapeHtml($css('text-3xl', 'dialog-inner-content-label')) ?>">
                        <span class="<?= $escaper->escapeHtml($css('text-[#cc0066]', 'dialog-inner-content-label-span')) ?>">
                            <?= $escaper->escapeHtml(__('Order faster')) ?>
                        </span>
                        <?= $escaper->escapeHtml(__('with iDEAL fast checkout')) ?>
                    </div>
                    <div class="<?= $escaper->escapeHtml($css('my-4', 'dialog-inner-content-teaser')) ?>">
                        <p><?= $escaper->escapeHtml(__('Create an iDEAL profile and save your address for your next order')) ?></p>
                    </div>
                    <form action="/paynl/checkout/fastcheckoutstart" method="post">
                        <input type="hidden" value="<?= $escaper->escapeHtml($shippingAddress->getCountryId()) ?>"
                               name="selected_estimate_country"/>
                        <input type="hidden" value="<?= $escaper->escapeHtml($shippingAddress->getPostcode()) ?>"
                               name="selected_estimate_zip"/>
                        <button class="<?= $escaper->escapeHtml($css('w-full bg-[#cc0066] text-white rounded-full p-4 my-2 font-bold', 'fast-checkout-button')) ?>"
                                type="submit"
                                title="Fast Checkout">
                            <?= $escaper->escapeHtml(__('Fast Checkout')) ?>
                        </button>
                        <?php echo /* @noEscape */ $block->getBlockHtml('formkey') ?>
                    </form>
                    <button @click.prevent="toggleModal"
                            class="<?= $escaper->escapeHtml($css('w-full border border-zinc-400 rounded-full p-4 my-2 font-bold', 'regular-button')) ?>">
                        <?= $escaper->escapeHtml(__('Enter my own address and pay')) ?>
                    </button>
                </div>
            </div>
        </div>
    </dialog>
</div>
