<?php
declare(strict_types=1);

use Magento\Framework\View\Element\Template;
use LokiCheckout\PayNl\ViewModel\IdealFastCheckout;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Field\ViewModel\ImageOutput;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var IdealFastCheckout $idealFastCheckout */

$idealFastCheckout = $viewModelFactory->create(IdealFastCheckout::class);
$shippingAddress = $idealFastCheckout->getShippingAddress();
$imageOutput = $viewModelFactory->create(ImageOutput::class);
?>
<form action="/paynl/checkout/fastcheckoutstart" method="post" x-data="LokiForm">
    <input type="hidden" value="<?= $escaper->escapeHtml($shippingAddress->getCountryId()) ?>" name="selected_estimate_country"/>
    <input type="hidden" value="<?= $escaper->escapeHtml($shippingAddress->getPostcode()) ?>" name="selected_estimate_zip"/>
    <a @click="submit" title="Fast Checkout"
       class="cursor-pointer rounded-md p-4 bg-[#c90066] text-white flex">
        <?= /* @noEscape */ $imageOutput->get('Paynl_Payment::images/fastCheckoutIdeal.png') ?>
        <span class="pt-4"><?= $escaper->escapeHtml(__('Fast Checkout')) ?></span>
    </a>

    <?php echo /* @noEscape */ $block->getBlockHtml('formkey') ?>
</form>
