<?php
declare(strict_types=1);

/** @version 2.0.10 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use LokiCheckout\PayNl\ViewModel\IdealFastCheckout;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Field\ViewModel\ImageOutput;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var IdealFastCheckout $idealFastCheckout */

$idealFastCheckout = $viewModelFactory->create(IdealFastCheckout::class);
$shippingAddress = $idealFastCheckout->getShippingAddress();
$imageOutput = $viewModelFactory->create(ImageOutput::class);
?>
<form action="/paynl/checkout/fastcheckoutstart" method="post" x-data="LokiForm">
    <input type="hidden" value="<?= $escaper->escapeHtml($shippingAddress->getCountryId()) ?>" name="selected_estimate_country"/>
    <input type="hidden" value="<?= $escaper->escapeHtml($shippingAddress->getPostcode()) ?>" name="selected_estimate_zip"/>
    <a @click.prevent="submit" title="Fast Checkout"
       class="<?= $css('cursor-pointer rounded-md p-4 bg-[#c90066] text-white flex', '@todo') ?>">
        <?= /* @noEscape */ $imageOutput->get('Paynl_Payment::images/fastCheckoutIdeal.png') ?>
        <span class="<?= $css('pt-4', '@todo') ?>"><?= $escaper->escapeHtml(__('Fast Checkout')) ?></span>
    </a>

    <?php echo /* @noEscape */ $block->getBlockHtml('formkey') ?>
</form>
