<?php
declare(strict_types=1);

/** @version 2.0.9 */

use Magento\Framework\View\Element\Template;
use LokiCheckout\PayNl\ViewModel\IdealFastCheckout;
use LokiCheckout\Core\ViewModel\CheckoutState;
use Loki\Components\Factory\ViewModelFactory;
use Loki\Components\Util\Block\ChildRenderer;

/** @var Template $block */
/** @var ViewModelFactory $viewModelFactory */
/** @var IdealFastCheckout $idealFastCheckout */
/** @var CheckoutState $checkoutState */
/** @var ChildRenderer $childRenderer */

$idealFastCheckout = $viewModelFactory->create(IdealFastCheckout::class);
if (false === $idealFastCheckout->enabled()) {
    return;
}
?>
<div>
    <?php if ($idealFastCheckout->modalEnabled()): ?>
        <?= /* @noEscape */ $childRenderer->html($block, 'modal') ?>
    <?php else: ?>
        <?= /* @noEscape */ $childRenderer->html($block, 'simple') ?>
    <?php endif; ?>
</div>
